version: '3.9'
services:
  server:
    container_name: ${PROJECT}-server
    platform: ${BUILD_PLATFORM}
    image: mcr.microsoft.com/devcontainers/dotnet:0-${DOTNET_VARIANT}
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./server/:/usr/src/server
    ports:
      - ${DOTNET_PORT}:${DOTNET_PORT}
    networks:
      - api-gateway
      - mssql-connection
    environment:
      - DOTNET_PORT=${DOTNET_PORT}
      - DOTNET_URLS=${DOTNET_URLS}
    command: sleep infinity
  mssql:
    container_name: ${PROJECT}-mssql
    # NOTE: Image is not available for linux/arm64/v8, enable rosetta for x86/amd64 emulation on apple silicon in docker settings
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:${MSSQL_VARIANT}
    restart: unless-stopped
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - mssql-data:/var/opt/mssql
    ports:
      - ${MSSQL_TCP_PORT}:${MSSQL_TCP_PORT}
    networks:
      - mssql-connection
    environment:
      - ACCEPT_EULA=${MSSQL_ACCEPT_EULA}
      - MSSQL_PID=${MSSQL_PID}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_TCP_PORT=${MSSQL_TCP_PORT}
  mssql-migration:
    container_name: ${PROJECT}-mssql-migration
    platform: ${BUILD_PLATFORM}
    image: mcr.microsoft.com/devcontainers/dotnet:0-${DOTNET_VARIANT}
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./database/:/usr/src/database
    networks:
      - mssql-connection
    command: sleep infinity
networks:
  api-gateway:
    name: ${PROJECT}-api-gateway
    driver: bridge
  mssql-connection:
    name: ${PROJECT}-mssql-connection
    driver: bridge
volumes:
  mssql-data:
