version: '3.9'
services:
  nginx:
    container_name: ${PROJECT}-nginx
    platform: ${BUILD_PLATFORM}
    image: nginx:${NGINX_VARIANT}
    restart: unless-stopped
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    networks:
      - api-gateway
  client:
    container_name: ${PROJECT}-client
    platform: ${BUILD_PLATFORM}
    image: ${PROJECT}-client-image
    build:
      context: ./Client
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ./Client/:/usr/src/Client
      - node_modules:/usr/src/Client/node_modules
    ports:
      - ${REACT_PORT}:${REACT_PORT}
    networks:
      - api-gateway
    environment:
      - REACT_PORT=${REACT_PORT}
  server:
    container_name: ${PROJECT}-server
    platform: ${BUILD_PLATFORM}
    image: ${PROJECT}-server-image
    build:
      context: ./Server
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ./Server/:/usr/src/Server
    ports:
      - ${DOTNET_PORT}:${DOTNET_PORT}
    networks:
      - api-gateway
      - mssql-connection
    environment:
      - DOTNET_PORT=${DOTNET_PORT}
      - DOTNET_URLS=${DOTNET_URLS}
      - MSSQL_APP_CONNECTION_STRING=${MSSQL_APP_CONNECTION_STRING}
      - MSSQL_APP_TEST_CONNECTION_STRING=${MSSQL_APP_TEST_CONNECTION_STRING}
  mssql:
    container_name: ${PROJECT}-mssql
    # NOTE: Image is not available for linux/arm64/v8, enable rosetta for x86/amd64 emulation on apple silicon in docker settings
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:${MSSQL_VARIANT}
    restart: unless-stopped
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - mssql-data:/var/opt/mssql
    ports:
      - ${MSSQL_TCP_PORT}:${MSSQL_TCP_PORT}
    networks:
      - mssql-connection
    environment:
      - ACCEPT_EULA=${MSSQL_ACCEPT_EULA}
      - MSSQL_PID=${MSSQL_PID}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_TCP_PORT=${MSSQL_TCP_PORT}
  mssql-migration:
    container_name: ${PROJECT}-mssql-migration
    platform: ${BUILD_PLATFORM}
    image: ${PROJECT}-mssql-migration-image
    build:
      context: ./Database
      dockerfile: ./.devcontainer/Dockerfile
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./Database/:/usr/src/Database
    networks:
      - mssql-connection
    environment:
      - MSSQL_APP_DATABASE=${MSSQL_APP_DATABASE}
      - MSSQL_APP_TEST_DATABASE=${MSSQL_APP_TEST_DATABASE}
      - MSSQL_SYSTEM_CONNECTION_STRING=${MSSQL_SYSTEM_CONNECTION_STRING}
      - MSSQL_APP_CONNECTION_STRING=${MSSQL_APP_CONNECTION_STRING}
      - MSSQL_APP_TEST_CONNECTION_STRING=${MSSQL_APP_TEST_CONNECTION_STRING}
networks:
  api-gateway:
    name: ${PROJECT}-api-gateway
    driver: bridge
  mssql-connection:
    name: ${PROJECT}-mssql-connection
    driver: bridge
volumes:
  node_modules:
  mssql-data:
